CREATE TABLE IF NOT EXISTS cdlevyt (
Levy_id INTEGER NOT NULL AUTO_INCREMENT,
Artisti VARCHAR(100) NOT NULL,
Albumi VARCHAR(100) NOT NULL,
BiisiLkm VARCHAR(4) NOT NULL,
Julkaisuvuosi VARCHAR(4),
Tyylilaji VARCHAR(50),
CONSTRAINT pk_cdlevyt PRIMARY KEY(Levy_id)
) ;

